# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RN_test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RN_test

  target 'RN_test-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RN_testTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
